---
- name: install and start servers
  yum:
    name:
      - "{{ ftp_package }}"
      - httpd
    state: latest

- name: start ftp server
  service:
    name: "{{ ftp_package }}"
    state: started
    enabled: true

- name: start web service
  service:
    name: httpd
    state:  started
    enabled: true
