---
- name: create some users
  hosts: all
  vars_files:
    - vars/users
    - vars/groups
  tasks:
    - name: create groups
      group:
        name: "{{ item.groupname }}"
      loop: "{{ usergroups }}"

    - name: create users
      user:
        name: "{{ item.username }}"
        groups: "{{ item.groups }}"
      loop: "{{ users }}"

    - name: add ssh keys
      authorized_key:
        user: "{{ item.username }}"
        key: "{{ lookup( 'file', 'files/' + item.username + '/id_rsa.pub') }}"
      loop: "{{ users }}"

    - name: add sales group members to sudo
      copy:
        content: "%sales ALL=(ALL) NOPASSWD: ALL"
        dest:  /etc/sudoers.d/sales
        mode: 0440

    - name: disable root ssh login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
      notify:  restart_sshd

  handlers:
    - name: restart_sshd
      service:
        name: sshd
        state: restarted
      
