---
- name: when demo
  gather_facts: yes
  hosts: all
  vars:
    supported_distros:
      - Ubuntu
      - CentOS
      - Fedora
      - RedHat
  tasks:
    - name: print distro
      debug:
        var: ansible_distribution

    - name: copy nginx repo file
      copy:
        src: nginx.repo
        dest:  /etc/yum.repos.d/nginx.repo
      when: ansible_distribution in supported_distros

    - name: Install nginx
      yum:
        name: nginx
        state: present
      when: ansible_distribution in supported_distros
