---
- name: using multiple conditions
  hosts: all
#  gather_facts: smart
  tasks:
  - package:
      name: httpd
      state: removed
    when: >
      ( ansible_distribution == "RedHat" and
        ansible_memfree_mb > 128 )
      or
      ( ansible_distribution == "CentOS" and
        ansible_memfree_mb > 128 )

