---
- name: using multiple conditions
  gather_facts: yes
  hosts: all
  tasks:
  - package:
      name: httpd
      state: installed
    when:
      - ansible_distribution == "RedHat"
      - ansible_memfree_mb > 256
